/**
 * Liste mondiale des pays pour l'onboarding (/bienvenue).
 *
 * Le wizard met en avant les 8 pays UEMOA (cf. COUNTRIES dans ./types.ts) en
 * accès rapide ; le bouton « Autre pays » ouvre une liste déroulante alimentée
 * par WORLD_COUNTRIES.
 *
 * `code` : ISO 3166-1 alpha-2 en minuscules — compatible avec flagcdn.com
 * (https://flagcdn.com/h24/<code>.png) pour afficher le vrai drapeau.
 * `label` : nom français du pays.
 *
 * La colonne profiles.country stocke ce `code` (texte libre — cf.
 * supabase/country_to_text.sql).
 */

export type WorldCountry = { code: string; label: string };

export const WORLD_COUNTRIES: WorldCountry[] = [
  { code: "af", label: "Afghanistan" },
  { code: "za", label: "Afrique du Sud" },
  { code: "al", label: "Albanie" },
  { code: "dz", label: "Algérie" },
  { code: "de", label: "Allemagne" },
  { code: "ad", label: "Andorre" },
  { code: "ao", label: "Angola" },
  { code: "ag", label: "Antigua-et-Barbuda" },
  { code: "sa", label: "Arabie saoudite" },
  { code: "ar", label: "Argentine" },
  { code: "am", label: "Arménie" },
  { code: "au", label: "Australie" },
  { code: "at", label: "Autriche" },
  { code: "az", label: "Azerbaïdjan" },
  { code: "bs", label: "Bahamas" },
  { code: "bh", label: "Bahreïn" },
  { code: "bd", label: "Bangladesh" },
  { code: "bb", label: "Barbade" },
  { code: "be", label: "Belgique" },
  { code: "bz", label: "Belize" },
  { code: "bj", label: "Bénin" },
  { code: "bt", label: "Bhoutan" },
  { code: "by", label: "Biélorussie" },
  { code: "mm", label: "Birmanie (Myanmar)" },
  { code: "bo", label: "Bolivie" },
  { code: "ba", label: "Bosnie-Herzégovine" },
  { code: "bw", label: "Botswana" },
  { code: "br", label: "Brésil" },
  { code: "bn", label: "Brunei" },
  { code: "bg", label: "Bulgarie" },
  { code: "bf", label: "Burkina Faso" },
  { code: "bi", label: "Burundi" },
  { code: "kh", label: "Cambodge" },
  { code: "cm", label: "Cameroun" },
  { code: "ca", label: "Canada" },
  { code: "cv", label: "Cap-Vert" },
  { code: "cl", label: "Chili" },
  { code: "cn", label: "Chine" },
  { code: "cy", label: "Chypre" },
  { code: "co", label: "Colombie" },
  { code: "km", label: "Comores" },
  { code: "cg", label: "Congo-Brazzaville" },
  { code: "cd", label: "Congo-Kinshasa (RDC)" },
  { code: "kr", label: "Corée du Sud" },
  { code: "kp", label: "Corée du Nord" },
  { code: "cr", label: "Costa Rica" },
  { code: "ci", label: "Côte d'Ivoire" },
  { code: "hr", label: "Croatie" },
  { code: "cu", label: "Cuba" },
  { code: "dk", label: "Danemark" },
  { code: "dj", label: "Djibouti" },
  { code: "dm", label: "Dominique" },
  { code: "eg", label: "Égypte" },
  { code: "ae", label: "Émirats arabes unis" },
  { code: "ec", label: "Équateur" },
  { code: "er", label: "Érythrée" },
  { code: "es", label: "Espagne" },
  { code: "ee", label: "Estonie" },
  { code: "us", label: "États-Unis" },
  { code: "et", label: "Éthiopie" },
  { code: "fj", label: "Fidji" },
  { code: "fi", label: "Finlande" },
  { code: "fr", label: "France" },
  { code: "ga", label: "Gabon" },
  { code: "gm", label: "Gambie" },
  { code: "ge", label: "Géorgie" },
  { code: "gh", label: "Ghana" },
  { code: "gr", label: "Grèce" },
  { code: "gd", label: "Grenade" },
  { code: "gt", label: "Guatemala" },
  { code: "gn", label: "Guinée" },
  { code: "gw", label: "Guinée-Bissau" },
  { code: "gq", label: "Guinée équatoriale" },
  { code: "gy", label: "Guyana" },
  { code: "ht", label: "Haïti" },
  { code: "hn", label: "Honduras" },
  { code: "hu", label: "Hongrie" },
  { code: "in", label: "Inde" },
  { code: "id", label: "Indonésie" },
  { code: "iq", label: "Irak" },
  { code: "ir", label: "Iran" },
  { code: "ie", label: "Irlande" },
  { code: "is", label: "Islande" },
  { code: "il", label: "Israël" },
  { code: "it", label: "Italie" },
  { code: "jm", label: "Jamaïque" },
  { code: "jp", label: "Japon" },
  { code: "jo", label: "Jordanie" },
  { code: "kz", label: "Kazakhstan" },
  { code: "ke", label: "Kenya" },
  { code: "kg", label: "Kirghizistan" },
  { code: "ki", label: "Kiribati" },
  { code: "kw", label: "Koweït" },
  { code: "la", label: "Laos" },
  { code: "ls", label: "Lesotho" },
  { code: "lv", label: "Lettonie" },
  { code: "lb", label: "Liban" },
  { code: "lr", label: "Liberia" },
  { code: "ly", label: "Libye" },
  { code: "li", label: "Liechtenstein" },
  { code: "lt", label: "Lituanie" },
  { code: "lu", label: "Luxembourg" },
  { code: "mk", label: "Macédoine du Nord" },
  { code: "mg", label: "Madagascar" },
  { code: "my", label: "Malaisie" },
  { code: "mw", label: "Malawi" },
  { code: "mv", label: "Maldives" },
  { code: "ml", label: "Mali" },
  { code: "mt", label: "Malte" },
  { code: "ma", label: "Maroc" },
  { code: "mh", label: "Marshall (Îles)" },
  { code: "mu", label: "Maurice" },
  { code: "mr", label: "Mauritanie" },
  { code: "mx", label: "Mexique" },
  { code: "fm", label: "Micronésie" },
  { code: "md", label: "Moldavie" },
  { code: "mc", label: "Monaco" },
  { code: "mn", label: "Mongolie" },
  { code: "me", label: "Monténégro" },
  { code: "mz", label: "Mozambique" },
  { code: "na", label: "Namibie" },
  { code: "nr", label: "Nauru" },
  { code: "np", label: "Népal" },
  { code: "ni", label: "Nicaragua" },
  { code: "ne", label: "Niger" },
  { code: "ng", label: "Nigeria" },
  { code: "no", label: "Norvège" },
  { code: "nz", label: "Nouvelle-Zélande" },
  { code: "om", label: "Oman" },
  { code: "ug", label: "Ouganda" },
  { code: "uz", label: "Ouzbékistan" },
  { code: "pk", label: "Pakistan" },
  { code: "pw", label: "Palaos" },
  { code: "ps", label: "Palestine" },
  { code: "pa", label: "Panama" },
  { code: "pg", label: "Papouasie-Nouvelle-Guinée" },
  { code: "py", label: "Paraguay" },
  { code: "nl", label: "Pays-Bas" },
  { code: "pe", label: "Pérou" },
  { code: "ph", label: "Philippines" },
  { code: "pl", label: "Pologne" },
  { code: "pt", label: "Portugal" },
  { code: "qa", label: "Qatar" },
  { code: "ro", label: "Roumanie" },
  { code: "gb", label: "Royaume-Uni" },
  { code: "ru", label: "Russie" },
  { code: "rw", label: "Rwanda" },
  { code: "kn", label: "Saint-Kitts-et-Nevis" },
  { code: "sm", label: "Saint-Marin" },
  { code: "vc", label: "Saint-Vincent-et-les-Grenadines" },
  { code: "lc", label: "Sainte-Lucie" },
  { code: "sb", label: "Salomon (Îles)" },
  { code: "sv", label: "Salvador" },
  { code: "ws", label: "Samoa" },
  { code: "st", label: "Sao Tomé-et-Principe" },
  { code: "sn", label: "Sénégal" },
  { code: "rs", label: "Serbie" },
  { code: "sc", label: "Seychelles" },
  { code: "sl", label: "Sierra Leone" },
  { code: "sg", label: "Singapour" },
  { code: "sk", label: "Slovaquie" },
  { code: "si", label: "Slovénie" },
  { code: "so", label: "Somalie" },
  { code: "sd", label: "Soudan" },
  { code: "ss", label: "Soudan du Sud" },
  { code: "lk", label: "Sri Lanka" },
  { code: "se", label: "Suède" },
  { code: "ch", label: "Suisse" },
  { code: "sr", label: "Suriname" },
  { code: "sz", label: "Eswatini" },
  { code: "sy", label: "Syrie" },
  { code: "tj", label: "Tadjikistan" },
  { code: "tz", label: "Tanzanie" },
  { code: "td", label: "Tchad" },
  { code: "cz", label: "Tchéquie" },
  { code: "th", label: "Thaïlande" },
  { code: "tl", label: "Timor oriental" },
  { code: "tg", label: "Togo" },
  { code: "to", label: "Tonga" },
  { code: "tt", label: "Trinité-et-Tobago" },
  { code: "tn", label: "Tunisie" },
  { code: "tm", label: "Turkménistan" },
  { code: "tr", label: "Turquie" },
  { code: "tv", label: "Tuvalu" },
  { code: "ua", label: "Ukraine" },
  { code: "uy", label: "Uruguay" },
  { code: "vu", label: "Vanuatu" },
  { code: "va", label: "Vatican" },
  { code: "ve", label: "Venezuela" },
  { code: "vn", label: "Viêt Nam" },
  { code: "ye", label: "Yémen" },
  { code: "zm", label: "Zambie" },
  { code: "zw", label: "Zimbabwe" },
].sort((a, b) => a.label.localeCompare(b.label, "fr"));

/** Codes des 8 pays UEMOA (mis en avant en accès rapide dans le wizard). */
export const UEMOA_CODES = new Set([
  "ci", "sn", "bj", "tg", "bf", "ml", "ne", "gw",
]);

const LABEL_BY_CODE: Record<string, string> = Object.fromEntries(
  WORLD_COUNTRIES.map((c) => [c.code, c.label]),
);

/** `true` si `code` correspond à un pays connu de la liste mondiale. */
export function isWorldCountryCode(code: unknown): code is string {
  return typeof code === "string" && code.toLowerCase() in LABEL_BY_CODE;
}

/** Nom français d'un pays à partir de son code ISO. Renvoie le code brut
 *  (majuscules) si inconnu. */
export function getCountryLabel(code: string | null | undefined): string {
  if (!code) return "—";
  return LABEL_BY_CODE[code.toLowerCase()] ?? code.toUpperCase();
}

/** URL du drapeau (flagcdn) pour un code ISO alpha-2. */
export function countryFlagUrl(code: string, height = 24): string {
  return `https://flagcdn.com/h${height}/${code.toLowerCase()}.png`;
}
